### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by st0at** [staffim/StaffimRollbarBundle#19]
Hi,
What about supporting Symfony 3? Now when I try to install bundle on Symfony 3 I get:
composer require staffim/rollbar-bundle
Using version ^1.2 for staffim/rollbar-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.0.3
    - Conclusion: don't install symfony/symfony v3.0.3
    - staffim/rollbar-bundle v1.2.0 requires symfony/http-kernel ~2.4
....

**Comment by megazoll** [comment]
Fixed in https://github.com/staffim/StaffimRollbarBundle/commit/9ee3888ead8710ddcd71a8fcb9103f6b4e47326e and tagged as `v1.3.0`

**Comment by st0at** [comment]
That was quick, thank you :)
