### ISSUE TITLE
Rules to exclude Exception/Error from notification

### ISSUE THREAD

**Issue by erichard** [staffim/StaffimRollbarBundle#7]
Hi,

I went through several use cases where I simply cannot fix an error so the best move would be to just not send them to Rollbar (as the pricing is on the error volume).

What is the best way to achieve this in your bundle ? I think about a Voter pattern. We could register Voter that decide if the error/exception has to be notified. It is Symfony style, but perhaps this is overcomplicated…

**Comment by teu** [comment]
You probably could just swallow the exceptions (or spool-log somewhere else). But seams a bit weird to have constant errors popping up.
